# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"open_json": "10_api.ipynb",
         "open_file": "10_api.ipynb",
         "mkdir": "10_api.ipynb",
         "clean_up_string": "10_api.ipynb",
         "error_printer": "10_api.ipynb",
         "time_str": "10_api.ipynb",
         "Directories": "10_api.ipynb",
         "FlaskonfAPI": "10_api.ipynb"}

modules = ["api.py"]

doc_url = "https://raynardj.github.io/flaskonf/"

git_url = "https://github.com/raynardj/flaskonf/tree/master/"

def custom_doc_links(name): return None
